= NMEA2000_mcp library for Arduino =

Inherited object for use NMEA2000 library for Arduino Boards with
MCP2515 CAN bus controller. See also NMEA2000 library.

To use this library, you will also need NMEA2000 library and
developed version of mcp_can library, which you can download from
https://github.com/peppeve/CAN_BUS_Shield until changes has been implemented
to original https://github.com/Seeed-Studio/CAN_BUS_Shield library.

== License ==

2015 Copyright (c) Kave Oy, www.kave.fi  All right reserved.

Author: Timo Lappalainen

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-
  1301  USA
